name: Run tests using Cypress Github Action
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config: baseUrl=${{ secrets.BASE_URL }}
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          #Var used by Cypress Action to deretrmine the run id
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}