name: Run Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Install dependencies
        run: npm install

      - name: Verify installation
        run: npx cypress verify

      - name: Run Cypress Tests
        run: npx cypress run --config baseUrl=${{ secrets.BASE_URL }}

      - name: Save Screenshots - On failure
        uses: actions/upload-artifact@master
        with:
          name: screenshots
          path: cypress/screenshots
          if: failure()

      - name: Save videos - Always
        uses: actions/upload-artifact@master
        with:
          name: videos
          path: cypress/videos